// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qdhfwqxntnkczrjsbywd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFkaGZ3cXhudG5rY3pyanNieXdkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgyNTg2OTQsImV4cCI6MjA2MzgzNDY5NH0.FkHIsVqIqHd73O_P68Q84dvwhKlorq_qjimcxa7F77g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);